In [13]:
import pandas as pd

data=pd.read_csv("D:\\2024학년도 트랙배정결과_240118.csv", encoding='cp949')

data2=data['Unnamed: 3']
print(data2)

dic={'로봇':0, '반도체':0, '전력전자':0, '임베디드':0, '자율주행':0, '통신':0}


for i in data2:
    if i=='로봇트랙':
        dic['로봇'] += 1
    if i=='반도체/에너지트랙':
        dic['반도체'] += 1
    if i=='5G통신트랙':
        dic['통신'] += 1
    if i=='전력전자트랙':
        dic['전력전자'] += 1
    if i=='임베디드시스템트랙':
        dic['임베디드'] += 1
    if i=='자율주행자동차트랙':
        dic['자율주행'] += 1

print(dic)

0          배정 결과
1           로봇트랙
2         전력전자트랙
3      반도체/에너지트랙
4         5G통신트랙
         ...
122       전력전자트랙
123    임베디드시스템트랙
124    임베디드시스템트랙
125       전력전자트랙
126         로봇트랙
Name: Unnamed: 3, Length: 127, dtype: object
{'로봇': 21, '반도체': 21, '전력전자': 21, '임베디드': 21, '자율주행': 21, '통신': 21}

In [22]:
import pandas as pd

df1=pd.read_excel("D:\\파일이름.xlsx")
df2=pd.read_excel("D:\\파일이름.xlsx")

len0=df1['male']

df3=pd.DataFrame()

for i in range(len0):
    if i==0:
        df3['male']=df1['male'][i]
        df3['female']=df1['female'][i]
    else:
        df3['male'][i]=df1['male'][i]+df1['male'][i-1]
        df3['female'][i]=df1['female'][i]+df1['female'][i-1]
    
df3.to_excel("D:\\파일이름.xlsx", index=False)

print(df3)

FileNotFoundError: [Errno 2] No such file or directory: 'D:\\파일이름.xlsx'

In [23]:
df1=pd.read_excel("D:\\score.xlsx")
df1

  name score
0  홍길동    80
1  일지매   강감찬
2  전우치    40

In [ ]:
import pandas as pd
df=pd.read_excel("D:\\졸업생의 취업 현황 (대학)_2024-01-271910737.xlsx",
                    header=7
                )

df

In [74]:

len0 = len(df['61.5'])

f=open("D:\\취업률 정리.txt", 'w', encoding='utf-8')

f.write("="*50)
f.write("\n")
f.write('공과대학')
f.write("\n")
f.write("\n")
f.write('0 '+"건축공학전공 "+ "주간 "+ "일반과정 "+ '\n') 
f.write("졸업자: 46 "+ "\n"+ "취업률: 61.5")
f.write("\n")
f.write("\n")

sum=[]
count=[]

sum1=61.5
count1=1

for i in range(len0):
    
    if str(df['공과대학'][i])!="nan":
        sum.append(sum1)
        count.append(count1)
        sum1=0
        count1=0

        f.write("="*50)
        f.write("\n")
        f.write(str(df['공과대학'][i])+' ')
        f.write("\n")
        f.write("\n")
    
    f.write(str(i+1)+ ' ')
    f.write(str(df['건축공학전공'][i])+' ')
    f.write(str(df['주간'][i])+' ')
    f.write(str(df['일반과정'][i])+' ')
    f.write("\n")
    f.write("졸업자: "+ str(df['33'][i]+df['13'][i])+'\n')
    f.write("취업률: "+str(df['61.5'][i])) ##취업률 정보
    f.write("\n")
    f.write("\n")

    sum1+=df['61.5'][i]
    count1+=1

sum.append(sum1)
count.append(count1)

f.write("="*50)
f.write("\n")
f.write('대대별 취업률 통계')
f.write("\n")

mylist=['공과', '보건', '인문사회', '철도', '융기']

for i in range(len(sum)):
    f.write(mylist[i])
    f.write(str(sum[i]/count[i]))
    f.write("\n")

f.write("="*50)
f.write("\n")

f.close()

In [ ]:
import pandas as pd

df=pd.read_csv("파일위치.csv", encoding="utf-8-sig")

code=[]

count=1

for i in df['종목코드']:
    if count==1 or count==2:
        count+=1
        continue
    if i =="nan":
        continue
    else:
        code.append(i)

print(code)

In [2]:
import pandas as pd
df=pd.read_csv("D:\\score.csv", encoding="utf-8-sig")

df

C:\Users\kimju\AppData\Local\Temp\ipykernel_20376\201628479.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

  Unnamed: 0  score
0        NaN     80
1        홍길동     50
2        일지매     40
3        전우치     60

In [18]:
##df.columns

df.rename(columns={"Unnamed: 0":"name"}, inplace = True)
df.columns

Index(['name', 'score'], dtype='object')

In [34]:
df

x = df["name"].isna()


count=0
for index, i in enumerate(x):
    if i==True:
        count+=1
        index_x = index

count, index_x

<class 'pandas.core.series.Series'>

(1, 0)

In [35]:
from collections import Counter
print(Counter(x))

Counter({False: 3, True: 1})

In [100]:
import pandas as pd
df=pd.read_excel("D:\\졸업생의 취업 현황 (대학)_2024-01-271910737.xlsx",
                    header=5
                )

df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,남,여,남.1,여.1,...,여.15,계.1,남.16,여.16,계.2,남.17,여.17,계.3,남.18,여.18
0,합계,NaN,NaN,NaN,NaN,NaN,1332,705,792,379,...,91.6,91.3,92.3,89.2,86.2,88.0,82.3,84.6,86.5,80.7
1,2022,국립한국교통대학교 _본교,공과대학,건축공학전공,주간,일반과정,33,13,17,6,...,100.0,95.7,94.1,100.0,95.7,94.1,100.0,87.0,88.2,83.3
2,NaN,NaN,NaN,건축학전공,주간,일반과정,20,12,18,9,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
3,NaN,NaN,NaN,나노고분자공학전공,주간,일반과정,31,16,16,3,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,94.7,93.8,100.0
4,NaN,NaN,NaN,도시・교통공학전공,주간,일반과정,23,11,16,8,...,100.0,95.8,93.8,100.0,95.8,93.8,100.0,91.7,93.8,87.5
5,NaN,NaN,NaN,산업경영공학전공,주간,일반과정,37,8,27,4,...,100.0,80.6,77.8,100.0,74.2,70.4,100.0,74.2,70.4,100.0
6,NaN,NaN,NaN,산업디자인전공,주간,일반과정,4,4,3,3,...,100.0,100.0,100.0,100.0,66.7,100.0,33.3,66.7,100.0,33.3
7,NaN,NaN,NaN,신소재공학전공,주간,일반과정,40,16,22,8,...,100.0,96.7,95.5,100.0,90.0,90.9,87.5,86.7,86.4,87.5
8,NaN,NaN,NaN,안전공학전공,주간,일반과정,29,5,18,4,...,100.0,86.4,88.9,75.0,77.3,77.8,75.0,72.7,72.2,75.0
9,NaN,NaN,NaN,안전공학전공,야간,일반과정,19,1,19,1,...,100.0,85.0,84.2,100.0,85.0,84.2,100.0,85.0,84.2,100.0
10,NaN,NaN,NaN,의료IT공학전공,주간,일반과정,9,6,7,3,...,66.7,90.0,100.0,66.7,90.0,100.0,66.7,90.0,100.0,66.7
11,NaN,NaN,NaN,커뮤니케이션디자인전공,주간,일반과정,1,10,0,6,...,100.0,100.0,0.0,100.0,83.3,0.0,83.3,83.3,0.0,83.3
12,NaN,NaN,NaN,토목공학전공,주간,일반과정,41,5,23,3,...,100.0,96.2,95.7,100.0,96.2,95.7,100.0,92.3,91.3,100.0
13,NaN,NaN,NaN,화공생물공학전공,주간,일반과정,36,22,25,12,...,91.7,91.9,92.0,91.7,89.2,88.0,91.7,89.2,88.0,91.7
14,NaN,NaN,NaN,환경공학전공,주간,일반과정,30,15,9,5,...,100.0,92.9,88.9,100.0,92.9,88.9,100.0,92.9,88.9,100.0
15,NaN,NaN,NaN,환경공학전공,야간,일반과정,14,4,11,1,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
16,NaN,NaN,보건생명대학,IT응용융합학과,야간,계약학과,6,5,6,5,...,80.0,81.8,83.3,80.0,81.8,83.3,80.0,81.8,83.3,80.0
17,NaN,NaN,NaN,간호학과,주간,일반과정,11,47,9,37,...,89.2,91.3,100.0,89.2,87.0,100.0,83.8,84.8,100.0,81.1
18,NaN,NaN,NaN,물리치료학과,주간,일반과정,23,19,19,17,...,94.1,97.2,100.0,94.1,97.2,100.0,94.1,97.2,100.0,94.1
19,NaN,NaN,NaN,물리치료학과,야간,일반과정,3,7,3,6,...,100.0,100.0,100.0,100.0,77.8,66.7,83.3,77.8,66.7,83.3
20,NaN,NaN,NaN,생명공학전공,주간,일반과정,7,11,5,4,...,100.0,88.9,80.0,100.0,33.3,40.0,25.0,33.3,40.0,25.0
21,NaN,NaN,NaN,식품공학전공,주간,일반과정,7,17,3,9,...,100.0,100.0,100.0,100.0,83.3,100.0,77.8,83.3,100.0,77.8
22,NaN,NaN,NaN,식품영양학전공,주간,일반과정,0,21,0,12,...,83.3,83.3,0.0,83.3,83.3,0.0,83.3,83.3,0.0,83.3
23,NaN,NaN,NaN,유아특수교육학과,주간,일반과정,2,10,0,8,...,100.0,100.0,0.0,100.0,100.0,0.0,100.0,100.0,0.0,100.0
24,NaN,NaN,NaN,응급구조학과,주간,일반과정,19,18,13,11,...,90.9,91.7,92.3,90.9,83.3,92.3,72.7,79.2,84.6,72.7
25,NaN,NaN,인문사회대학,경영학전공,주간,일반과정,21,14,11,8,...,87.5,89.5,100.0,75.0,84.2,90.9,75.0,78.9,81.8,75.0
26,NaN,NaN,NaN,국제통상전공,주간,일반과정,17,12,5,3,...,66.7,75.0,80.0,66.7,62.5,60.0,66.7,62.5,60.0,66.7
27,NaN,NaN,NaN,비즈니스영어전공,주간,일반과정,11,17,8,6,...,100.0,92.9,87.5,100.0,85.7,87.5,83.3,71.4,75.0,66.7
28,NaN,NaN,NaN,사회복지학전공,주간,일반과정,10,19,6,8,...,100.0,78.6,66.7,87.5,71.4,66.7,75.0,71.4,66.7,75.0
29,NaN,NaN,NaN,스포츠건강관리학전공,주간,일반과정,11,5,6,4,...,100.0,80.0,66.7,100.0,80.0,66.7,100.0,70.0,66.7,75.0
30,NaN,NaN,NaN,스포츠산업학전공,주간,일반과정,9,5,5,2,...,100.0,71.4,60.0,100.0,57.1,40.0,100.0,57.1,40.0,100.0
31,NaN,NaN,NaN,영어영문학전공,주간,일반과정,18,33,5,14,...,92.9,89.5,100.0,85.7,73.7,100.0,64.3,68.4,100.0,57.1
32,NaN,NaN,NaN,유아교육학과,주간,일반과정,0,28,0,17,...,82.4,82.4,0.0,82.4,76.5,0.0,76.5,76.5,0.0,76.5
33,NaN,NaN,NaN,융합경영전공,주간,일반과정,24,15,14,10,...,90.0,87.5,100.0,70.0,83.3,92.9,70.0,83.3,92.9,70.0
34,NaN,NaN,NaN,음악학과,주간,일반과정,5,20,2,6,...,50.0,50.0,50.0,50.0,37.5,50.0,33.3,37.5,50.0,33.3
35,NaN,NaN,NaN,중국어전공,주간,일반과정,15,35,10,19,...,84.2,79.3,70.0,84.2,72.4,60.0,78.9,72.4,60.0,78.9
36,NaN,NaN,NaN,한국어문학전공,주간,일반과정,10,19,3,4,...,100.0,85.7,66.7,100.0,57.1,33.3,75.0,57.1,33.3,75.0
37,NaN,NaN,NaN,항공서비스학과,주간,일반과정,1,16,0,8,...,75.0,75.0,0.0,75.0,75.0,0.0,75.0,75.0,0.0,75.0
38,NaN,NaN,NaN,항공운항학과,주간,일반과정,28,0,25,0,...,0.0,100.0,100.0,0.0,100.0,100.0,0.0,100.0,100.0,0.0
39,NaN,NaN,NaN,행정정보학전공,주간,일반과정,11,13,3,7,...,85.7,80.0,100.0,71.4,80.0,100.0,71.4,80.0,100.0,71.4
40,NaN,NaN,NaN,행정학전공,주간,일반과정,60,46,40,15,...,93.3,96.4,97.5,93.3,90.9,90.0,93.3,89.1,87.5,93.3
41,NaN,NaN,철도대학,철도경영・물류학전공,주간,일반과정,33,16,21,11,...,90.9,87.5,90.5,81.8,87.5,90.5,81.8,87.5,90.5,81.8
42,NaN,NaN,NaN,철도운전시스템전공,주간,일반과정,38,8,33,7,...,100.0,97.5,97.0,100.0,95.0,93.9,100.0,95.0,93.9,100.0
43,NaN,NaN,NaN,철도인프라시스템공학전공,주간,일반과정,29,3,18,2,...,100.0,95.0,94.4,100.0,90.0,88.9,100.0,90.0,88.9,100.0
44,NaN,NaN,NaN,철도전기전자전공,주간,일반과정,38,5,22,5,...,100.0,96.3,95.5,100.0,96.3,95.5,100.0,92.6,90.9,100.0
45,NaN,NaN,NaN,철도차량시스템전공,주간,일반과정,50,8,27,5,...,100.0,87.5,85.2,100.0,87.5,85.2,100.0,87.5,85.2,100.0
46,NaN,NaN,NaN,컴퓨터정보공학전공,주간,일반과정,26,4,12,1,...,100.0,92.3,91.7,100.0,84.6,83.3,100.0,84.6,83.3,100.0
47,NaN,NaN,융합기술대학,기계공학전공,주간,일반과정,60,6,39,3,...,100.0,90.5,89.7,100.0,85.7,87.2,66.7,85.7,87.2,66.7
48,NaN,NaN,NaN,기계공학전공,야간,일반과정,20,1,12,1,...,0.0,84.6,91.7,0.0,69.2,75.0,0.0,69.2,75.0,0.0
49,NaN,NaN,NaN,소프트웨어학전공,주간,일반과정,30,8,18,2,...,100.0,95.0,94.4,100.0,85.0,88.9,50.0,85.0,88.9,50.0
50,NaN,NaN,NaN,자동차공학전공,주간,일반과정,45,3,28,1,...,100.0,86.2,85.7,100.0,86.2,85.7,100.0,82.8,82.1,100.0
51,NaN,NaN,NaN,전기공학전공,주간,일반과정,42,5,22,3,...,66.7,84.0,86.4,66.7,76.0,77.3,66.7,72.0,72.7,66.7
52,NaN,NaN,NaN,전기공학전공,야간,일반과정,21,1,9,1,...,100.0,90.0,88.9,100.0,70.0,66.7,100.0,70.0,66.7,100.0
53,NaN,NaN,NaN,전자공학과,주간,일반과정,111,21,48,10,...,100.0,94.8,95.8,90.0,87.9,89.6,80.0,87.9,89.6,80.0
54,NaN,NaN,NaN,컴퓨터공학전공,주간,일반과정,44,7,24,4,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
55,NaN,NaN,NaN,항공・기계설계전공,주간,일반과정,49,9,27,7,...,85.7,97.1,100.0,85.7,91.2,92.6,85.7,91.2,92.6,85.7

In [101]:
df.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', '남', '여', '남.1', '여.1', '남.2', '여.2', '남.3', '여.3', '남.4',
       '여.4', '남.5', '여.5', '남.6', '여.6', '남.7', '여.7', 'Unnamed: 22', '남.8',
       '여.8', 'Unnamed: 25', 'Unnamed: 26', '남.9', '여.9', '남.10', '여.10',
       '남.11', '여.11', '남.12', '여.12', 'Unnamed: 35', '남.13', '여.13', '남.14',
       '여.14', '계', '남.15', 'Unnamed: 42', '여.15', '계.1', '남.16', '여.16',
       '계.2', '남.17', '여.17', '계.3', '남.18', '여.18'],
      dtype='object')

In [61]:
df['Unnamed: 35']##취업률

df['Unnamed: 2']##대학
df['Unnamed: 3']##학과

df['Unnamed: 4']##주야간

df['남']
df['여']

61.5

In [102]:
df.rename(columns={'Unnamed: 35':"취업률", 
                   'Unnamed: 2':"대학", 
                   'Unnamed: 3':"학과",
                   'Unnamed: 4':"주야간"},
                   inplace=True )

df.columns

Index(['Unnamed: 0', 'Unnamed: 1', '대학', '학과', '주야간', 'Unnamed: 5', '남', '여',
       '남.1', '여.1', '남.2', '여.2', '남.3', '여.3', '남.4', '여.4', '남.5', '여.5',
       '남.6', '여.6', '남.7', '여.7', 'Unnamed: 22', '남.8', '여.8', 'Unnamed: 25',
       'Unnamed: 26', '남.9', '여.9', '남.10', '여.10', '남.11', '여.11', '남.12',
       '여.12', '취업률', '남.13', '여.13', '남.14', '여.14', '계', '남.15',
       'Unnamed: 42', '여.15', '계.1', '남.16', '여.16', '계.2', '남.17', '여.17',
       '계.3', '남.18', '여.18'],
      dtype='object')

In [116]:
import numpy as np

df['대학']
df2=df['대학'].replace(np.nan, '')
df2

##type(df2[2])

0
1       공과대학
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16    보건생명대학
17
18
19
20
21
22
23
24
25    인문사회대학
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41      철도대학
42
43
44
45
46
47    융합기술대학
48
49
50
51
52
53
54
55
Name: 대학, dtype: object

In [122]:
count=0

print(len(df2))

for i in df2:
    if i!='':
        print(count)
    count+=1

56
1
16
25
41
47

In [115]:
len0=len(df['학과'])

f=open("D:\\취업률 정리-수정.txt", 'w', encoding='utf-8')

sum=[]
count=[]

sum1 = 0
count1 = 0

f.write("="*50)
f.write("\n")

for i in range(1, len0):
    f.write("#"*10+' '+ df2[i]+'\n')

    f.write(str(i)+ ' ')
    f.write(df['학과'][i]+' ')
    f.write(df['주야간'][i]+' ')
    
    f.write("\n")
    f.write("졸업자: "+ str(df['남'][i]+df['여'][i])+'\n')
    f.write("취업률: "+ str(df['취업률'][i])) ##취업률 정보
    f.write("\n")
    f.write("\n")

sum=[]

sum.append(df['취업률'][1:16].sum())
sum.append(df['취업률'][16:25].sum())
sum.append(df['취업률'][25:41].sum())
sum.append(df['취업률'][41:47].sum())
sum.append(df['취업률'][47:].sum())

count=[15, 9, 16, 6, 9]

f.write("="*50)
f.write("\n")
f.write('대대별 취업률 통계')
f.write("\n")

mylist=['공과', '보건', '인문사회', '철도', '융기']

for i in range(len(sum)):
    f.write(mylist[i])
    f.write(str(sum[i]/count[i]))
    f.write("\n")

f.write("="*50)
f.write("\n")

f.close()